function logTodayFunction() { last | grep "$(date '+%a %b %e')" }

alias myip='curl -s ip.appspot.com | pbcopy;pbpaste'
alias flush_dns='sudo dscacheutil -flushcache'
alias hosts='atom /etc/hosts'
alias lock='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend'
alias landown='sudo ifconfig en0 down'
alias lanup='sudo ifconfig en0 up'
alias feierabend='sudo shutdown -h now'
alias andsim='~/Library/Android/sdk/tools/emulator -avd Nexus &'
alias openxcode='open ios/*.xcworkspace'
alias xcodecopy='cp -R /Users/rafael/Documents/wdr/xcodenewsapp/. ios/.'
alias gdc='git diff --check'
alias shakeit='adb shell input keyevent 82'
alias logtoday='logTodayFunction'
alias rns='npm run start'
alias rnios='react-native run-ios --simulator "iPhone 8"'
alias buchmal='sh /Users/rafael/Documents/macroLEA.sh'
alias podi='cd ios && pod install & cd ..'
alias l='exa -l'
